language: python

sudo: false

env:
  global:
    - secure: "mn3RZC/TCt+zx8HK1LYFplCAWiSE+19mJ6S7JgVRggbpizbSln73/KtTXvLvZbJHwxK1n5m8yK6gFS3gZBpFKdOnQtkkT+yinaEYFV7eX+3kPxv4KX97spIHHMGKl/jIrewMbLBe4Drz8XcAUdWDWA4iFPrA1tVDhbnGTiZ2NEvMdn4Q4QXWfYhOzfJizSLnjqiuiNYI9cFVERf6mD5S5aVqRd2OivKR85FbCZPzAn6gcxl5XKIzvqFhMTffXXhe1vq4/pWuu+2vj5sb36gAKoh8fPW+WvieuAtKY4VqCZ4GPIA7iMLxqDXkGXD2s5KsBPXN0j9f5zyL7KCDqmYgw08gxa9GM+eEdtC2lQLtGpV2mmoau3hG6FevJkD9qraORoQiul4ZmBwCqznqDvE61MkbMnA0XCutLb/bhFlcrUrLRvCkiF5xpm8t6NNWKI5kqP1MQUlRFCxoaUn+xdwAGKbwXdyC+w9HhZR9lNuotfg0XVLCVTeP3GIWIhuZJMiJsfCpm71HnaFXsq7B9J0mq4wEinIBDeNCJxAZN2phQHH5ElBkl+EyDy+8p3czLLSQ/WhfHVW7Ylv3oRNab5YTFFTKTVY5plGx6nbzHQG6YS9wAPTGEeHyPGheLI0/fpZZ/8m4WLBx/VUYAPpkYe42a8xpdbeoz6lx7Xj3jAmo+Lg="

matrix:
  fast_finish: true
  include:
  - python: 3.6
    env: TEST_TARGET=default
  - python: 3.6
    env: TEST_TARGET=coding_standards
  - python: 3.6
    env: TEST_TARGET=docs

before_install:
  - wget http://bit.ly/miniconda -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
  - conda update conda
  - conda config --add channels conda-forge --force
  - conda create --name TEST python=$TRAVIS_PYTHON_VERSION --file requirements.txt --file requirements-dev.txt
  - source activate TEST

install:
  - python setup.py sdist && version=$(python setup.py --version) && pushd dist && pip install erddapy-${version}.tar.gz && popd

script:
  - if [[ $TEST_TARGET == 'default' ]]; then
      cp -r tests/ /tmp ;
      pushd /tmp && pytest -rxs tests && popd ;
    fi

  - if [[ $TEST_TARGET == 'coding_standards' ]]; then
      flake8 --max-line-length=105 erddapy --exclude=_version.py ;
      flake8 --max-line-length=105 tests ;
    fi

  - if [[ $TEST_TARGET == 'docs' ]]; then
      set -e ;
      cp notebooks/{quick_intro.ipynb,searchfor.ipynb} docs/source/ ;
      pushd docs ;
      make clean html linkcheck ;
      popd ;
      python -m doctr deploy --sync .;
      python -m doctr deploy --sync --no-require-master --built-docs docs/build/html "docs-$TRAVIS_BRANCH" ;
    fi

doctr:
  require-master: true
  sync: false

deploy:
  skip_cleanup: true
  provider: pypi
  user: ocefpaf
  password:
    secure: HD3oiZ3aWzGlmMpoZqsu8uG6v7Zhk/VgqrU+Ch0y0MQFCl8Dagh8Wuo6iLKGWimqSQ3vl3CpXZAhCZRyv/iEZLVf3f5rDiPpQNgvAARZANxMolidGEa+HBhzNOPtJQ78d76ikJ9fe575cO5FEzJi+7NgHFXucyjr+1kINDjPXNvhLeUEaT+C7+uOYrCc0hkznDs0sCwsNGIYvy+cyjQL2FsLmoqRzwsliCTSXNBLJ3fw15BlXGRbHCXT1qf+8kNAGdR650a3c+jazz76ElIdjsg7E//bWmxiePHgBuctnIXNTdMxEi2rMC2QqURV/UEdZMb361bAk3avu1/vuTrOiO86As1hzh+luQVF/jK0x90mpPSlCYN2cyvx2eliLgrDNSzmIiL1H5YYlXSqLX80hb2+YQE8hNwe53SGAhYBO1bktyAuIno4+vK54wShnpqK/alcwvpB3uwx3QNCUKcKEQwzTs6bJVSYWySCyy7fuIGFX+mwdzOOyLrhnWIIimyolpITzbfOqCf/5FnGXoIZ7Kjm4CTGqqaEos4wG2CXDsz8dlgU8xSz1nImZlg6mM+6h/hLxaUtRsw79ZLZZ8/IsKUewWTi/FPJPB8Dri8+3Qa74JppNWVkb7DxNYYErxOGRF6GHGRtsBb4I2stupD2VNGKHFZO1Cg+G9RyUOHAlT4=
  distributions: sdist bdist_wheel
  upload_docs: no
  on:
    repo: pyoceans/erddapy
    tags: true
    python: 3.6
    all_branches: master
    condition: '$TEST_TARGET == "default"'
